baseURL = 'https://atsuchiy.github.io/TechBlog/'
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = true
googleAnalytics = "G-WG3D1JYEXB"
hasCJKLanguage = true
theme = "hugo-PaperMod"
title = 'Tech Blog'

[params]
ShowCodeCopyButtons = true
# ShowBreadcrumbs = true
env = "production"

[languages]

[languages.ja]
contentDir = "content/ja"
languageName = "Japanese"
weight = 1

[languages.ja.menus]
[[languages.ja.menus.main]]
identifier = "tags"
name = "タグ一覧"
pageRef = "tags.md"
weight = 10

[[languages.ja.menus.main]]
identifier = "search"
name = "検索"
pageRef = "search.md"
weight = 20

[languages.en]
contentDir = "content/en"
languageName = "English"
weight = 2
[languages.en.menus]
[[languages.en.menus.main]]
identifier = "tags"
name = "All Tags"
pageRef = "tags.md"
weight = 10

[[languages.en.menus.main]]
identifier = "search"
name = "Search"
pageRef = "search.md"
weight = 20

# [menus]
# main = [
#     { identifier = "tags", name = "Tags", pageRef = "tags.md", weight = 10 },
#     { identifier = "search", name = "Search", pageRef = "search.md", weight = 20 }
# ]

[fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
limit = 10
keys = ["title", "permalink", "summary", "content"]

[outputs]
home = ["HTML", "RSS", "JSON"]
